name: Build Windows Executable

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # make manually build

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.7.2'
        host: 'windows'
        target: 'desktop'
        arch: 'win64_msvc2019_64'

    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build Project
      run: cmake --build build --config Release

    - name: Package Application with DLLs
      shell: pwsh
      run: |
        New-Item -ItemType Directory -Force -Path MyCalculator-Windows
        $exePath = Get-ChildItem -Path build -Filter MyCalculator.exe -Recurse | Select-Object -First 1
        if (-not $exePath) { throw "Executable not found!" }
        Copy-Item $exePath.FullName -Destination MyCalculator-Windows\
        windeployqt MyCalculator-Windows\MyCalculator.exe

    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: MyCalculator-Windows-exe
        path: MyCalculator-Windows/
